inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - paid_up.gemspec
    - db/migrate/*
    - spec/dummy/db/schema.rb
    - spec/dummy/db/migrate/*

Metrics/BlockLength:
  Exclude:
    - spec/*
    - spec/*/*
    - spec/*/*/*
    - spec/dummy/db/seeds/*

Metrics/ModuleLength:
  Exclude:
    - spec/*
    - spec/*/*
    - spec/*/*/*

