AllCops:
  Exclude:
    - paid_up.gemspec
    - db/migrate/*
    - spec/dummy/db/schema.rb
    - spec/dummy/db/migrate/*
Style/ClassVars:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
