# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: subscription_features 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "subscription_features"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Karen Lundgren"]
  s.date = "2015-04-06"
  s.description = "Allows a model of your choosing (such as users) to subscribe to a plan, which enables features."
  s.email = "karen.e.lundgren@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/models/feature.rb",
    "app/models/features_plan.rb",
    "app/models/plan.rb",
    "app/models/subscription.rb",
    "config/routes.rb",
    "lib/generators/subscription_features/install/install_generator.rb",
    "lib/generators/subscription_features/install/templates/initializer.rb",
    "lib/generators/subscription_features/install/templates/migrate/create_features_plans_table.rb",
    "lib/generators/subscription_features/install/templates/migrate/create_features_table.rb",
    "lib/generators/subscription_features/install/templates/migrate/create_plans_table.rb",
    "lib/generators/subscription_features/install/templates/migrate/create_subscriptions_table.rb",
    "lib/generators/subscription_features/utils.rb",
    "lib/subscription_features.rb",
    "lib/subscription_features/concerns/models/feature.rb",
    "lib/subscription_features/concerns/models/features_plan.rb",
    "lib/subscription_features/concerns/models/plan.rb",
    "lib/subscription_features/concerns/models/subscription.rb",
    "lib/subscription_features/concerns/models/user.rb",
    "lib/subscription_features/configuration.rb",
    "lib/subscription_features/engine.rb",
    "lib/subscription_features/localization.rb",
    "lib/subscription_features/railtie.rb",
    "lib/subscription_features/version.rb",
    "spec/dummy/README.rdoc",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/images/.keep",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/stylesheets/application.css",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/concerns/.keep",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/mailers/.keep",
    "spec/dummy/app/models/.keep",
    "spec/dummy/app/models/concerns/.keep",
    "spec/dummy/app/models/user.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/bin/bundle",
    "spec/dummy/bin/rails",
    "spec/dummy/bin/rake",
    "spec/dummy/bin/setup",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/assets.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/cookies_serializer.rb",
    "spec/dummy/config/initializers/filter_parameter_logging.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/subscription_features.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/config/secrets.yml",
    "spec/dummy/db/development.sqlite3",
    "spec/dummy/db/migrate/20150403211031_create_features_table.rb",
    "spec/dummy/db/migrate/20150403211032_create_features_plans_table.rb",
    "spec/dummy/db/migrate/20150403211033_create_plans_table.rb",
    "spec/dummy/db/migrate/20150403211034_create_subscriptions_table.rb",
    "spec/dummy/db/test.sqlite3",
    "spec/dummy/lib/assets/.keep",
    "spec/dummy/log/.keep",
    "spec/dummy/log/development.log",
    "spec/dummy/log/test.log",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/models/user_spec.rb",
    "spec/rails_helper.rb",
    "spec/spec_helper.rb",
    "spec/subscription_features_spec.rb",
    "subscription_features.gemspec"
  ]
  s.homepage = "http://github.com/nerakdon/subscription_features"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Allows a model of your choosing to subscribe to a plan, which enables features."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 4.2"])
      s.add_runtime_dependency(%q<rails-i18n>, [">= 0"])
      s.add_runtime_dependency(%q<haml-rails>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<subscription_features>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<devise>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 4.2"])
      s.add_dependency(%q<rails-i18n>, [">= 0"])
      s.add_dependency(%q<haml-rails>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<subscription_features>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 4.2"])
    s.add_dependency(%q<rails-i18n>, [">= 0"])
    s.add_dependency(%q<haml-rails>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<subscription_features>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
  end
end

